# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89dd9e505eecb6cfecfe2b515c9dd6a1bc18acb92910bf081958453f740a860c20c82240c8c8dc08b4ca7847e7b373e3f85c1e54ea1c1b6c91a4357c1d16d2bb

test:
  secret_key_base: a222b15fd7d1c997b52e552c53a462e1124ab46aadec08110ddd84f6bb7cfa6d4637bda31b4b16c129e8acaa745a58f7f77fe37af97305d4f5df211d42fbd673

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
